services:
  barracuda-localization:
    build:
      context: .
      dockerfile: Dockerfile
    user: root
    container_name: barracuda-localization
    tty: true
    network_mode: host
    restart: always
    volumes:
      - $HOME/.ssh:/root/.ssh
      - $HOME/.gitconfig:/root/.gitconfig
    environment:
      - ROS_MASTER_URI=${ROS_MASTER_URI}
      - ROS_IP=${ROS_IP}
