services:
  barracuda-localization:
    build:
      context: .
      dockerfile: Dockerfile
    user: root
    container_name: barracuda-localization
    tty: true
    network_mode: host
    restart: always
    volumes:
      - $HOME/.ssh:/root/.ssh
